### ISSUE TITLE
Improve NormalizationFailedException error messages

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#388] opened 2019-06-05 16:57 UTC
At this [line](https://github.com/Sp2000/colplus-backend/blob/1a9fb1efbaf61fdf102fb62935b889de4eaf176e/colplus-ws/src/main/java/org/col/importer/acef/AcefInserter.java#L101) and this [line](https://github.com/Sp2000/colplus-backend/blob/1a9fb1efbaf61fdf102fb62935b889de4eaf176e/colplus-ws/src/main/java/org/col/importer/acef/AcefInserter.java#L112) it would help to have a more descriptive error message that specify which ACEF file (and possibly column) failed to read. Also, it should [delete the Neo4j normalizer database that it created](https://github.com/Sp2000/colplus-backend/issues/382).

@mdoering, what does "log to db" mean? Is there a log of database errors that I can look at?

**Comment by mdoering** [comment] 2019-06-05 21:39
"log to db" is meant to say it is stored with this message as a failed import in the import metrics history: http://api-dev.col.plus/importer?state=failed

In general you need to check the Kibana logs for details:
https://logs.gbif.org/goto/d2ebae5b4d0d8e8cc3d718414029dcfc

A silly one that should not throw is this one, when the metadata does not specify the exact dataset type:
> java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:882)
	at org.col.api.model.Dataset.setType(Dataset.java:75)
	at org.col.importer.acef.AcefInserter.readMetadata(AcefInserter.java:202)
	at org.col.importer.NeoInserter.insertAll(NeoInserter.java:58)
	at org.col.importer.Normalizer.insertData(Normalizer.java:806)
	at org.col.importer.Normalizer.call(Normalizer.java:77)
	at org.col.importer.ImportJob.importDataset(ImportJob.java:184)
	at org.col.importer.ImportJob.run(ImportJob.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

(logged as #390)

**Comment by mdoering** [comment] 2019-06-05 21:40
This one might be one of your ACEF reader problems. It also seems like a code bug, but I cant say what it exactly is without looking at it in more detail:
> Dataset 2071 import failed. Failed to read ACEF files. Log to db
--
t stack_trace |   | org.col.importer.NormalizationFailedException: Failed to read ACEF files 	at org.col.importer.acef.AcefInserter.batchInsert(AcefInserter.java:101) 	at org.col.importer.NeoInserter.insertAll(NeoInserter.java:74) 	at org.col.importer.Normalizer.insertData(Normalizer.java:806) 	at org.col.importer.Normalizer.call(Normalizer.java:77) 	at org.col.importer.ImportJob.importDataset(ImportJob.java:184) 	at org.col.importer.ImportJob.run(ImportJob.java:113) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.IllegalArgumentException: Key.hashCode() changed after serialization, make sure to use correct Key Serializer 	at org.mapdb.HTreeMap.put(HTreeMap.kt:315) 	at org.col.importer.neo.NeoDb.create(NeoDb.java:525) 	at org.col.importer.NeoInserter.lambda$insertEntities$2(NeoInserter.java:125) 	at org.col.importer.NeoInserter.lambda$processVerbatim$1(NeoInserter.java:100) 	at java.util.Iterator.forEachRemaining(Iterator.java:116) 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) 	at org.col.importer.NeoInserter.processVerbatim(NeoInserter.java:98) 	at org.col.importer.NeoInserter.insertEntities(NeoInserter.java:119) 	at org.col.importer.acef.AcefInserter.batchInsert(AcefInserter.java:62)

**Comment by mdoering** [comment] 2019-06-05 21:50
The stacktrace of the error log identifies well where things go wrong. 
It just does not say which exact record and value the evil one is. Thats quite hard to log

**Comment by mdoering** [comment] 2019-06-05 22:10
Closing unless you think this is highly important

**Closed by mdoering** 2019-06-05 22:10 UTC
Labels: enhancement, wontfix

**Comment by gdower** [comment] 2019-06-05 23:54
@mdoering, I think it's fine to close this for now although it took a pretty substantial amount of time isolating the bug in #389. It will only be highly important if we hit importer problems a lot.
