### ISSUE TITLE
DELETE not working on sectors

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#359] opened 2019-05-20 10:47 UTC
Gives 204, but the sector is still there after reload

**Comment by ayco-at-naturalis** [comment] 2019-05-20 11:06
Does this relate to the search index?

**Comment by mdoering** [comment] 2019-05-20 12:44
what is the path you use? It is not a regular CRUD delete `DELETE /sector/{key}' which should give you a 405. But instead an asynchroneous sector deletion should be triggered in the assembly resource which also removes catalogue data `DELETE /assembly/3/sync/{sectorKey}`

**Comment by thomasstjerne** [comment] 2019-05-20 13:34
I use:
```DELETE https://api-dev.col.plus/assembly/3/sync/2876```

**Comment by mdoering** [comment] 2019-05-20 16:50
The resource assembly paths are confusing.
The sync delete I mentioned and you use are canceling a scheduled or running sync just like with imports. To delete the sector it is this:
`DELETE https://api-dev.col.plus/assembly/3/sector/2876`

Now that we have a single backend I am inclined to move all sector related things under /sector/{key}.
Would this not be better?
CRUD sector:
`POST https://api-dev.col.plus/sector`
`GET https://api-dev.col.plus/sector/2876`
`PUT https://api-dev.col.plus/sector/2876`
`DELETE https://api-dev.col.plus/sector/2876`

schedule syncs and cancel them
`POST https://api-dev.col.plus/sector/2876/sync`
`DELETE https://api-dev.col.plus/sector/2876/sync`

list sync metadata/get specific attempt
`GET https://api-dev.col.plus/sector/2876/sync`
`GET https://api-dev.col.plus/sector/2876/sync/{attempt}`

list sync queue/history
`GET https://api-dev.col.plus/dataset/{catalogueKey}/sync`

**Comment by mdoering** [comment] 2019-05-21 16:01
moved path discussion to #364

**Comment by mdoering** [comment] 2019-05-24 21:37
sector deletes are working for me.
There was a bug when deleting sector that caused the sectors themselves to remain, only deleting the taxa. Fixed in https://github.com/Sp2000/colplus-backend/commit/dd109a4374898c95ca68f7a710defb90b18d5d31

**Comment by gdower** [comment] 2019-11-06 20:20
Sector deletes aren't working again:

```
DELETE https://api-dev.col.plus/sector/20018

204 No Content
```

```JSON
GET https://api-dev.col.plus/sector/20018

200 OK
{
  "created": "2019-11-06T17:58:17.659205",
  "createdBy": 102,
  "modified": "2019-11-06T18:00:19.054853",
  "modifiedBy": 102,
  "key": 20018,
  "datasetKey": 3,
  "target": {
    "id": "77ee75a5-a4d0-4837-b99c-815ce0d3a2f7",
    "name": "Maxillopoda",
    "rank": "class"
  },
  "subjectDatasetKey": 2066,
  "subject": {
    "name": "Lycopodiacae",
    "rank": "family"
  },
  "mode": "attach"
}
```

**Comment by gdower** [comment] 2019-11-06 21:23
Whatever the problem is, it's specific to sector 20018, because delete works for other sectors.

**Closed by gdower** 2019-11-06 21:23 UTC
