### ISSUE TITLE
Correcting ranks with decisions might not work properly

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#638] opened 2020-02-24 21:49 UTC
@yroskov tried to fix the [name parser issue with the author `des Loges` being misinterpreted as infraspecies _Sepidium integrum des_](https://github.com/Sp2000/colplus-backend/issues/624) with a decision:

http://api.catalogue.life/decision/12715
```JSON
{
  "created": "2020-02-24T21:30:45.564363",
  "createdBy": 102,
  "modified": "2020-02-24T21:30:45.564363",
  "modifiedBy": 102,
  "key": 12715,
  "datasetKey": 3,
  "subject": {
    "id": "1048-1146",
    "name": "Sepidium integrum des",
    "authorship": "Loges, 1881",
    "rank": "species",
    "code": "zoological",
    "status": "synonym",
    "parent": "Sepidium variegatum"
  },
  "subjectDatasetKey": 1206,
  "mode": "update",
  "name": {
    "scientificName": "Sepidium integrum",
    "authorship": "Desbrochers des Loges, 1881",
    "rank": "species",
    "candidatus": false,
    "parsed": false,
    "formattedName": "Sepidium integrum Desbrochers des Loges, 1881"
  }
}
```

However, it doesn't look like this type of decision works properly, because even after syncing the name [still is being included as _Sepidium integrum des_](https://data.catalogue.life/catalogue/3/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=Sepidium%20integrum%20des&sortBy=taxonomic).

**Comment by mdoering** [comment] 2020-03-09 12:32
The problem is not that the decision being applied.
The problem rather is that the name is still given as single scientificName and authorship strings that need to be parsed. Which results in the exact same problem as you tried to fix.

In this case it should be given as parsed pieces. Giving the full name only helps to fix data errors, not name parsing ones.

We need to find a better way of fixing parsing problems. The original design fixed the parsing in the names index in one place for the entire clearinghouse. I still think thats the best place to do it - we just need to build it

**Comment by mdoering** [comment] 2020-03-10 07:31
closing in favor of #160 that should be adressed soon

**Closed by mdoering** 2020-03-10 07:31 UTC
Labels: bug, decisions
