### ISSUE TITLE
400: sector does have a non existing subject

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#424] opened 2019-07-15 16:47 UTC
When doing a sector sync, I'm getting a "Sector 2728 does have a non existing subject CLASS Lycopodiopsida for dataset 1140" error after syncing the newly imported dataset, however, sector sync works after re-importing the unmodified dataset again.

Here's the [logs narrowed down to this morning](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:'2019-07-15T12:44:03.634Z',mode:absolute,to:'2019-07-15T16:44:03.635Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:sector,negate:!f,type:phrase,value:'2728'),query:(match:(sector:(query:2728,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:attempt,negate:!f,type:phrase,value:'4'),query:(match:(attempt:(query:4,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))),index:AWGthDPVf8lu3pmEwvFE,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))).

Steps to reproduce:

1. Import World Ferns
2. After the import succeeds try to sync the Lycopodiopsida sector and it will give the following error:

![image](https://user-images.githubusercontent.com/8573609/61232395-d27a3980-a6f3-11e9-93aa-2bb0f9af0fca.png)

3. Re-import World Ferns
4. After the import succeeds try to sync the Lycopodiopsida sector again and this time sector sync works

**Comment by gdower** [comment] 2019-07-17 16:36
Additionally when I get the 400 non-existing subject error, the sector attachment point does not display in the assembly source viewer (see Polypodiopsida below), so it seems like the sector sometimes isn't recognized by the importer even though it is actually present. The sector is recognized for Lycopodiopsida, and that sector synced successfully.

![image](https://user-images.githubusercontent.com/8573609/61392323-2582f680-a884-11e9-94c7-caae30205004.png)

After re-importing the unmodified dataset it looks like this and Polypodiopsida but not Lycopodiopsida syncs:

![image](https://user-images.githubusercontent.com/8573609/61393470-a2af6b00-a886-11e9-9a9c-f651d3c4b9fd.png)

**Comment by mdoering** [comment] 2019-08-16 09:29
I imported Ferns for the very first time into dev.
The sectors then look good and do not report to be broken:
https://dev.col.plus/dataset/1140/sectors

Syncing Lycopodiopsida then works just fine.
Closing as I cannot reproduce this anymore with latest code

**Closed by mdoering** 2019-08-16 09:29 UTC
Labels: bug, import
