### ISSUE TITLE
chinese char encoding looks wrong

### ISSUE THREAD

**Issue by MortenHofft** [Sp2000/colplus-backend#56] opened 2018-03-05 13:13 UTC
http://api.col.plus/taxon/7/info

**Comment by ayco-at-naturalis** [comment] 2018-03-05 13:42
It certainly is wrong, but at least in this case the html entities really are in the source data (not caused by some charset encoding conversion issue in the ACEF zip generation.

**Comment by mdoering** [comment] 2018-03-05 14:38
We should read and replace them during import though. The non verbatim JSON should not have them anymore. Maybe even remove them from the verbatim?

**Comment by mdoering** [comment] 2018-03-05 16:07
see also Sp2000/colplus#37 and #53

**Comment by mdoering** [comment] 2018-03-07 17:20
Fixed via #60

**Closed by mdoering** 2018-03-07 17:20 UTC
